In [8]:
from typing import Generator
import pandas as pd
from pathlib import Path

In [93]:
predicted_features_dir = Path("/home/bhkuser/bhklab/katy/readii_2_roqc/data/procdata/TCIA_RADCURE_oral_cavity/features/pyradiomics/original_none_none_n")

sample_feature_files = sorted(predicted_features_dir.rglob("*.csv"))

predicted_features_df = pd.DataFrame()

    # dataset_features_path.parent.mkdir(parents=True, exist_ok=True)

# Generator
def non_empty_dfs(file_list:list[Path]) -> Generator[pd.DataFrame, list[Path], None]:
    for file in file_list:
        try:
            file_df = pd.read_csv(file, index_col=0, header=None, sep=";")
            if not file_df.empty:
                yield file_df.T
        except pd.errors.EmptyDataError:
            pass

try:
    # Find all non-empty feature dataframes in the globbed list and concatenate them
    dataset_features = pd.concat(non_empty_dfs(sample_feature_files))
    # Sort the dataframes by the sample ID column
    dataset_features = dataset_features.sort_values(by="SampleID")
    # Save out the combined feature dataframe
    # dataset_features.to_csv(dataset_features_path, index=False)

except ValueError:
    # Handle case where all dataframes are empty
    # print(f"No non-empty dataframes found for {permutation} {region}.")
    # Create empty dataframe for compiled dataset features
    dataset_features = pd.DataFrame()

In [94]:
dataset_features.set_index('SampleID', inplace=True)

In [95]:
ground_truth_features = pd.read_csv("/home/bhkuser/bhklab/katy/readii_2_roqc/data/results/TCIA_RADCURE/features/pyradiomics/pyradiomics_h4h_all_images_features/original_full_features.csv")
ground_truth_features.set_index('SampleID', inplace=True)

In [96]:
ground_truth_oral_cavity = ground_truth_features[ground_truth_features.index.isin(dataset_features.index)]

In [79]:
dataset_features.iloc[:, 49:]

,original_shape_VoxelVolume,original_shape_SurfaceArea,original_shape_SurfaceVolumeRatio,original_shape_Sphericity,original_shape_Compactness1,original_shape_SphericalDisproportion,original_shape_Maximum3DDiameter,original_shape_Maximum2DDiameterSlice,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,...,gradient_gldm_SmallDependenceHighGrayLevelEmphasis,gradient_gldm_SmallDependenceLowGrayLevelEmphasis,gradient_ngtdm_Busyness,gradient_ngtdm_Coarseness,gradient_ngtdm_Complexity,gradient_ngtdm_Contrast,gradient_ngtdm_Strength,SeriesInstanceUID_Image,Modality_Image,SeriesInstanceUID_Mask
SampleID,,,,,,,,,,,,,,,,,,,,,
RADCURE-0014_0008,102784.0,21354.06415475376,0.2080080604886651,0.4965204805647213,0.018561139189166072,2.0140156129363334,117.83887304281215,75.8023746329889,90.0499861188218,107.18675291284833,...,1.0739279619171733,0.0034195096094457467,75.25304577397856,0.00016355666768997536,235.7359306739939,0.0008383823418024504,2.0733258125262126,NaN,NaN,NaN
RADCURE-0040_0030,13276.0,3438.8722252759394,0.25966000757156693,0.7871824463422652,0.03705202756644193,1.2703535306797253,44.9221548904324,44.10215414239989,44.91102314577124,31.016124838541646,...,28.193420473181163,0.0062500616124920765,16.457120564512902,0.0006775516511963527,785.3029955256529,0.11453930245923336,1.0763525573181538,0,CT,0
RADCURE-0067_0053,18238.0,4583.746595811855,0.2518991905594051,0.7298933548011426,0.03308171314215099,1.370063165285903,49.09175083453431,37.656340767525464,38.948684188300895,48.27007354458868,...,0.7381516959751026,0.0033384243091802756,28.89280344241732,0.0010262231354041882,30.71638521646888,0.0015217655559408771,1.024599063417443,0,CT,0
RADCURE-0115_0091,24268.0,7847.172831376822,0.32448066620557453,0.5153716227378906,0.019628161817508177,1.9403474228703959,68.044103344816,61.204574992397426,37.8021163428716,67.77905281132217,...,33.01816270781405,0.005635796792647592,10.712513400392192,0.00033092847219369856,3682.8719221180554,0.015120898153572284,12.258972121272233,0,CT,0
RADCURE-0137_0108,14446.0,7350.326689131701,0.5110663561173454,0.3891022264556489,0.01287639974232321,2.5700187046192173,65.1536645170477,63.788713735268246,48.104053883222775,61.40032573203501,...,186.06361886661045,0.008833410849645021,1.1363676270659673,0.0007569257859588192,21915.740818021826,0.08353463723389372,17.15997117522595,0,CT,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RADCURE-3087_2452,82290.0,16079.205175078936,0.19558409979676053,0.5686437042066983,0.02274883861207651,1.7585704239794178,84.77617589865682,73.60027173862879,71.69379331573968,79.30952023559341,...,0.6366369445473089,0.0034705616098762654,87.77169232705472,0.0001701757163225102,139.44406729669515,0.0006733892743896061,0.7714428145685424,0,CT,0
RADCURE-3091_2456,26088.0,7384.963864317731,0.28368065242327833,0.5751946724842233,0.023143080143074545,1.7385418325956914,64.47480127925948,49.92995093127971,53.225933528685054,57.688820407423826,...,1.4480251351606652,0.00424630119494445,28.298156740620847,0.00043153045653372864,250.98349768486415,0.0010008337649780612,3.5022025391422864,0,CT,0
RADCURE-3118_2480,51894.0,8916.60066653174,0.17202887533824163,0.7539631474552798,0.03473154117150925,1.3263247724708103,63.96092557178953,60.8276253029822,52.20153254455275,54.20332093147061,...,54.234866136190675,0.004943823918005525,30.387844263994136,0.00023195909943443948,1706.6908010242396,0.16423482741087309,0.4406783542751555,0,CT,0
RADCURE-3252_2606,130824.0,21382.641752979285,0.16356036473722815,0.5825657627393923,0.023589368426851456,1.7165444040132252,92.20086767487604,79.40403012442127,80.62257748298549,86.6083136886985,...,6.886659631273972,0.00362892123947607,84.2002334531049,8.300406697332643e-05,842.3075239888717,0.0038801079753225482,1.480880707292309,0,CT,0
RADCURE-3268_2622,17206.0,4583.624631236059,0.26700596392654746,0.7021024173168733,0.031210417581545746,1.4242936291567836,46.42197755374064,44.40720662234904,46.32493928760188,39.11521443121589,...,12.928974465079413,0.005363688626195417,11.49300234822278,0.0005028215781200045,1310.279113597614,0.013142859601512322,5.145450458293822,0,CT,0

In [80]:
ground_truth_oral_cavity.iloc[:, 49:]

,original_shape_VoxelVolume,original_shape_SurfaceArea,original_shape_SurfaceVolumeRatio,original_shape_Sphericity,original_shape_Compactness1,original_shape_SphericalDisproportion,original_shape_Maximum3DDiameter,original_shape_Maximum2DDiameterSlice,original_shape_Maximum2DDiameterColumn,original_shape_Maximum2DDiameterRow,...,gradient_gldm_LargeDependenceLowGrayLevelEmphasis,gradient_gldm_LowGrayLevelEmphasis,gradient_gldm_SmallDependenceEmphasis,gradient_gldm_SmallDependenceHighGrayLevelEmphasis,gradient_gldm_SmallDependenceLowGrayLevelEmphasis,gradient_ngtdm_Busyness,gradient_ngtdm_Coarseness,gradient_ngtdm_Complexity,gradient_ngtdm_Contrast,gradient_ngtdm_Strength
SampleID,,,,,,,,,,,,,,,,,,,,,
RADCURE-0014_0008,110694.0,21809.923329,0.197260,0.510787,0.019367,1.957762,103.759337,75.133215,82.225300,94.366308,...,417.180225,0.729451,0.039397,11.682718,0.004020,18.065148,0.000151,3466.137441,0.001872,10.922218
RADCURE-0040_0030,9712.0,4089.329399,0.423171,0.536525,0.020849,1.863848,53.018865,44.407207,48.836462,37.013511,...,253.849441,0.582905,0.145612,32.216178,0.006629,14.087743,0.000850,713.442826,0.125674,1.368918
RADCURE-0067_0053,31018.0,8608.449316,0.278069,0.553869,0.021868,1.805480,68.549252,58.549125,45.694639,64.078077,...,443.212159,0.801924,0.032027,2.578640,0.004419,32.172288,0.000402,219.003732,0.004037,1.499349
RADCURE-0115_0091,28150.0,9410.101041,0.335304,0.474599,0.017346,2.107040,69.606034,66.370174,49.040799,68.593003,...,235.566709,0.590557,0.092678,43.685636,0.006005,9.714427,0.000285,5693.634692,0.016570,14.570511
RADCURE-0137_0108,16434.0,8628.250721,0.527093,0.361342,0.011523,2.767462,65.314623,63.505905,49.254441,64.381674,...,79.468297,0.255604,0.218928,109.408546,0.008303,1.331670,0.000680,17477.022664,0.045791,17.871338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RADCURE-3087_2452,83434.0,18510.787274,0.222226,0.498287,0.018660,2.006876,89.783072,77.369245,71.112587,83.006024,...,379.334077,0.705695,0.051666,146.795463,0.004487,5.129726,0.000174,42499.633167,0.004608,276.145892
RADCURE-3091_2456,20442.0,9384.745919,0.460841,0.384275,0.012638,2.602302,71.624018,62.936476,53.665631,62.201286,...,325.708551,0.760042,0.023498,1.310587,0.005801,27.075878,0.000474,253.858625,0.001302,3.076739
RADCURE-3118_2480,34450.0,8522.995912,0.247822,0.600059,0.024660,1.666504,63.600314,63.529521,52.773099,56.859476,...,319.363268,0.568723,0.182341,67.346142,0.005466,17.532411,0.000369,1933.187539,0.226579,0.552154
RADCURE-3252_2606,116104.0,20919.911794,0.180350,0.549820,0.021629,1.818778,90.658701,83.354664,67.268120,85.492690,...,526.358707,0.858111,0.040429,5.625570,0.003674,72.675126,0.000099,743.351849,0.002532,1.835736
RADCURE-3268_2622,17770.0,5397.216465,0.304535,0.609073,0.025218,1.641840,51.874849,51.088159,51.788030,39.408121,...,388.731555,0.738888,0.073786,15.091291,0.005612,10.428826,0.000501,1604.673596,0.009264,8.704728

In [81]:
ground_truth_oral_cavity

,Image,Mask,DatasetName,SeriesInstanceUID_Image,Modality_Image,SeriesInstanceUID_Mask,Modality_Mask,MaskID,readii_Permutation,readii_Region,...,gradient_gldm_LargeDependenceLowGrayLevelEmphasis,gradient_gldm_LowGrayLevelEmphasis,gradient_gldm_SmallDependenceEmphasis,gradient_gldm_SmallDependenceHighGrayLevelEmphasis,gradient_gldm_SmallDependenceLowGrayLevelEmphasis,gradient_ngtdm_Busyness,gradient_ngtdm_Coarseness,gradient_ngtdm_Complexity,gradient_ngtdm_Contrast,gradient_ngtdm_Strength
SampleID,,,,,,,,,,,,,,,,,,,,,
RADCURE-0014_0008,mit_RADCURE_GTVp/RADCURE-0014_0008/CT_00540914...,mit_RADCURE_GTVp/RADCURE-0014_0008/RTSTRUCT_59...,RADCURE_GTVp,1.3.6.1.4.1.14519.5.2.1.1908851512930714401385...,CT,1.3.6.1.4.1.14519.5.2.1.2184698074225477714557...,RTSTRUCT,ROI__[GTVp],original,full,...,417.180225,0.729451,0.039397,11.682718,0.004020,18.065148,0.000151,3466.137441,0.001872,10.922218
RADCURE-0040_0030,mit_RADCURE_GTVp/RADCURE-0040_0030/CT_09221213...,mit_RADCURE_GTVp/RADCURE-0040_0030/RTSTRUCT_01...,RADCURE_GTVp,1.3.6.1.4.1.14519.5.2.1.1024191190602940770844...,CT,1.3.6.1.4.1.14519.5.2.1.1722622404895709670231...,RTSTRUCT,ROI__[GTVp],original,full,...,253.849441,0.582905,0.145612,32.216178,0.006629,14.087743,0.000850,713.442826,0.125674,1.368918
RADCURE-0067_0053,mit_RADCURE_GTVp/RADCURE-0067_0053/CT_46272171...,mit_RADCURE_GTVp/RADCURE-0067_0053/RTSTRUCT_65...,RADCURE_GTVp,1.3.6.1.4.1.14519.5.2.1.1294532276908516679395...,CT,1.3.6.1.4.1.14519.5.2.1.1475886751570967777179...,RTSTRUCT,ROI__[GTVp],original,full,...,443.212159,0.801924,0.032027,2.578640,0.004419,32.172288,0.000402,219.003732,0.004037,1.499349
RADCURE-0115_0091,mit_RADCURE_GTVp/RADCURE-0115_0091/CT_78672115...,mit_RADCURE_GTVp/RADCURE-0115_0091/RTSTRUCT_19...,RADCURE_GTVp,1.3.6.1.4.1.14519.5.2.1.8328782971701368011591...,CT,1.3.6.1.4.1.14519.5.2.1.3644771453354617217384...,RTSTRUCT,ROI__[GTVp],original,full,...,235.566709,0.590557,0.092678,43.685636,0.006005,9.714427,0.000285,5693.634692,0.016570,14.570511
RADCURE-0137_0108,mit_RADCURE_GTVp/RADCURE-0137_0108/CT_44322590...,mit_RADCURE_GTVp/RADCURE-0137_0108/RTSTRUCT_13...,RADCURE_GTVp,1.3.6.1.4.1.14519.5.2.1.1550971881300336966021...,CT,1.3.6.1.4.1.14519.5.2.1.3350070453377912701688...,RTSTRUCT,ROI__[GTVp],original,full,...,79.468297,0.255604,0.218928,109.408546,0.008303,1.331670,0.000680,17477.022664,0.045791,17.871338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RADCURE-3087_2452,mit_RADCURE_GTVp/RADCURE-3087_2452/CT_32313804...,mit_RADCURE_GTVp/RADCURE-3087_2452/RTSTRUCT_64...,RADCURE_GTVp,1.3.6.1.4.1.14519.5.2.1.2411258050665649090448...,CT,1.3.6.1.4.1.14519.5.2.1.1805019043179251000156...,RTSTRUCT,ROI__[GTVp],original,full,...,379.334077,0.705695,0.051666,146.795463,0.004487,5.129726,0.000174,42499.633167,0.004608,276.145892
RADCURE-3091_2456,mit_RADCURE_GTVp/RADCURE-3091_2456/CT_45612952...,mit_RADCURE_GTVp/RADCURE-3091_2456/RTSTRUCT_69...,RADCURE_GTVp,1.3.6.1.4.1.14519.5.2.1.1743349180700898705402...,CT,1.3.6.1.4.1.14519.5.2.1.2802544132675954494230...,RTSTRUCT,ROI__[GTVp],original,full,...,325.708551,0.760042,0.023498,1.310587,0.005801,27.075878,0.000474,253.858625,0.001302,3.076739
RADCURE-3118_2480,mit_RADCURE_GTVp/RADCURE-3118_2480/CT_39407639...,mit_RADCURE_GTVp/RADCURE-3118_2480/RTSTRUCT_20...,RADCURE_GTVp,1.3.6.1.4.1.14519.5.2.1.2900758485754004722977...,CT,1.3.6.1.4.1.14519.5.2.1.1330177067608709608930...,RTSTRUCT,ROI__[GTVp],original,full,...,319.363268,0.568723,0.182341,67.346142,0.005466,17.532411,0.000369,1933.187539,0.226579,0.552154
RADCURE-3252_2606,mit_RADCURE_GTVp/RADCURE-3252_2606/CT_02683636...,mit_RADCURE_GTVp/RADCURE-3252_2606/RTSTRUCT_68...,RADCURE_GTVp,1.3.6.1.4.1.14519.5.2.1.1813496861290053850345...,CT,1.3.6.1.4.1.14519.5.2.1.2348944905916192865043...,RTSTRUCT,ROI__[GTVp],original,full,...,526.358707,0.858111,0.040429,5.625570,0.003674,72.675126,0.000099,743.351849,0.002532,1.835736
RADCURE-3268_2622,mit_RADCURE_GTVp/RADCURE-3268_2622/CT_32188665...,mit_RADCURE_GTVp/RADCURE-3268_2622/RTSTRUCT_60...,RADCURE_GTVp,1.3.6.1.4.1.14519.5.2.1.6539782063986376828293...,CT,1.3.6.1.4.1.14519.5.2.1.3128044068726822272315...,RTSTRUCT,ROI__[GTVp],original,full,...,388.731555,0.738888,0.073786,15.091291,0.005612,10.428826,0.000501,1604.673596,0.009264,8.704728

In [97]:
correlations = dataset_features.iloc[:, 49:-3].astype(float).corrwith(ground_truth_oral_cavity.iloc[:, 49:].astype(float), numeric_only=True, axis='index')
correlations.sort_values(ascending=False)

0
wavelet-HLH_glszm_ZoneVariance         0.993084
wavelet-HLH_glszm_LargeAreaEmphasis    0.992909
wavelet-LHH_glszm_ZoneVariance         0.988852
wavelet-LHH_glszm_LargeAreaEmphasis    0.988370
wavelet-HLL_glszm_ZoneVariance         0.985631
                                         ...
square_glszm_GrayLevelVariance        -0.032132
wavelet-HLH_firstorder_Skewness       -0.188332
wavelet-LLH_firstorder_Skewness       -0.224069
wavelet-HLH_firstorder_Mean           -0.369501
square_firstorder_Minimum                   NaN
Length: 1317, dtype: float64

In [98]:
correlations[correlations > 0.7].sort_values(ascending=False)

0
wavelet-HLH_glszm_ZoneVariance                        0.993084
wavelet-HLH_glszm_LargeAreaEmphasis                   0.992909
wavelet-LHH_glszm_ZoneVariance                        0.988852
wavelet-LHH_glszm_LargeAreaEmphasis                   0.988370
wavelet-HLL_glszm_ZoneVariance                        0.985631
                                                        ...
wavelet-LHH_firstorder_Range                          0.706219
wavelet-HLL_glcm_Idn                                  0.706063
wavelet-LHL_firstorder_RobustMeanAbsoluteDeviation    0.705844
wavelet-HHL_glszm_ZonePercentage                      0.705820
wavelet-HLH_glszm_GrayLevelNonUniformityNormalized    0.705420
Length: 816, dtype: float64

In [100]:
816/1317

0.6195899772209568

In [68]:
246/1317

0.1867881548974943